/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "ExpenseReportWebApp": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "ExpenseReports": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ExpensesApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}