/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ExpenseReportWebApp": {
      "type": "sst.aws.Astro"
      "url": string
    }
    "ExpenseReports": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ExpensesApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
  }
}
